-- Presto code to fetch quarter dates dynamically
WITH CURRENT_QUARTER AS (
  SELECT LAST_DAY_OF_MONTH (
      CASE
        WHEN MONTH (CURRENT_DATE) <= 3 THEN 
        CAST(
          CAST(YEAR (CURRENT_DATE) -1 AS VARCHAR) || '-' || '12' || '-' || '01' AS DATE
        )
        ELSE IF (
          LAST_DAY_OF_MONTH (
            CAST(
              CAST(YEAR (CURRENT_DATE) AS VARCHAR) || '-' || 
              CAST(LPAD (CAST((MONTH (CURRENT_DATE) / 3) * 3 AS VARCHAR), 2, '0' ) AS VARCHAR ) || '-' || 
              '01' AS DATE ) ) > CURRENT_DATE,
          CAST( 
            CAST(YEAR (CURRENT_DATE) AS VARCHAR) || '-' || 
            CAST(LPAD (CAST(((MONTH (CURRENT_DATE) / 3) - 1) * 3 AS VARCHAR), 2, '0' ) AS VARCHAR ) || '-' || 
            '01' AS DATE
          ),
          CAST(
            CAST(YEAR (CURRENT_DATE) AS VARCHAR) || '-' || 
            CAST(LPAD (CAST((MONTH (CURRENT_DATE) / 3) * 3 AS VARCHAR), 2, '0' ) AS VARCHAR ) || '-' ||
             '01' AS DATE
          )
        )
      END
    ) AS CURRENT_QUARTER
)
SELECT CURRENT_QUARTER AS CURRENTQUARTER,
  CURRENT_QUARTER - INTERVAL '3' MONTH AS PREVIOUSQUARTER,
  CURRENT_QUARTER - INTERVAL '6' MONTH AS SECONDLASTQUARTER,
  CURRENT_QUARTER - INTERVAL '9' MONTH AS THIRDLASTQUARTER,
  CURRENT_QUARTER - INTERVAL '12' MONTH AS FOURTHLASTQUARTER,
  CURRENT_QUARTER - INTERVAL '15' MONTH AS FIFTHLASTQUARTER,
  CURRENT_QUARTER - INTERVAL '18' MONTH AS SIXTHLASTQUARTER,
  CURRENT_QUARTER - INTERVAL '21' MONTH AS SEVENTHLASTQUARTER,
  CURRENT_QUARTER - INTERVAL '24' MONTH AS EIGHTHLASTQUARTER
FROM CURRENT_QUARTER
